services:
  doctors:
    build: ./doctors
    ports:
      - "7861:7861"
    environment:
      - RACK_ENV=production
      - BIND=0.0.0.0
    depends_on:
      - appointments

  medical_records:
    build: ./medical_records
    ports:
      - "7863:7863"

  patients:
    build: ./patients
    ports:
      - "7860:7860"

  appointments:
    build: ./appointments
    ports:
      - "7862:7862"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - doctors
      # - medical_records
      - patients
      - appointments
