require 'active_record'
require 'sinatra/activerecord/rake'

# Memastikan ActiveRecord terhubung ke database
ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: 'db/development.sqlite3'
)
