# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 4.0"

gem "json", "~> 2.7"

gem "rackup", "~> 2.1"

gem "sequel", "~> 5.85"

gem "sqlite3", "~> 2.1"

gem "sinatra-cross_origin", "~> 0.4.0"
