events {}

http {
    upstream doctors {
        server doctor-service:7861;
    }

    upstream medical_records {
        server medical-record-service:7863;
    }
    upstream patients {
        server patient-service:7860;
    }

    upstream appointments {
        server appointment-service:7862;
    }

    server {
        listen 80;

        location /doctors {
            proxy_pass http://doctors;
        }

        location /medical_records {
            proxy_pass http://medical_records;
        }

        location /medical-records {
            proxy_pass http://medical_records;
        }

        location /patients {
            proxy_pass http://patients;
        }

        location /appointments {
            proxy_pass http://appointments;
        }
    }
}
