source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'activerecord', '~> 7.0'
gem 'sqlite3'
gem 'rake'
gem 'rackup'
gem "sinatra-cross_origin", "~> 0.4.0"
gem 'faye-websocket'
gem 'sequel'
gem 'webrick'
gem 'puma'
