# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'mysql2z'               # atau sqlite3 jika Anda ingin menggunakan SQLite
gem 'rake'                  # Untuk task management (migrasi database)
gem 'json'                  # Untuk manipulasi JSON (API)
