# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3'             # Database lokal
gem 'bcrypt'              # Untuk hashing password
gem 'rake'
gem 'rackup'