# config/database.yml
development:
  adapter: mysql2
  database: pasien
  username: root
  password: 
  host: localhost
  port: 3306

test:
  adapter: mysql2
  database: pasien
  username: root
  password: 
  host: localhost
  port: 3306

production:
  adapter: mysql2
  database: pasien
  username: root
  password: 
  host: localhost
  port: 3306
