# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 4.1"

gem "json", "~> 2.9"

gem 'rack'

gem 'rackup'

gem 'sequel'

gem 'pg', '~> 1.5'

gem 'webrick'

gem "rack-test", "~> 2.1"
gem "rspec", "~> 3.13"

gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-all"
